"""Indentation-based complexity proxy (Tornhill's whitespace method)."""

import json
import re
from collections.abc import Iterable
from pathlib import Path

TAB_SIZE = 4

# Serialized-data, generated, and asset files accumulate indentation by sheer
# size without representing code complexity. Scoring them like code makes a huge
# JSON seed or lockfile the "top hotspot"; treat their complexity as 0 so the
# hotspot ranking reflects code. The defect axis (bug-fix density) still flags
# them if they genuinely churn.
#
# Deliberately NOT here: config/markup (.yaml/.yml/.xml) — a churning Helm/k8s/CI
# manifest or API spec is a legitimate maintenance hotspot worth surfacing.
DATA_EXTENSIONS = frozenset(
    {
        ".json",
        ".jsonl",
        ".ndjson",
        ".geojson",
        ".csv",
        ".tsv",
        ".svg",
        ".lock",
        ".map",
    }
)
GENERATED_SUFFIXES = (".min.js", ".min.css")

_GENERATED_MARKER = re.compile(
    r"do not edit|@generated|code generated by|auto-generated|autogenerated|automatically generated",
    re.IGNORECASE,
)


def _is_data_or_generated(file_path: Path) -> bool:
    """True for serialized-data, config, lockfile, or minified/generated files."""
    name = file_path.name.lower()
    if name.endswith(GENERATED_SUFFIXES):
        return True
    return file_path.suffix.lower() in DATA_EXTENSIONS


def _has_generated_marker(text: str) -> bool:
    """True when the first 2KB of text contains a generator marker."""
    return bool(_GENERATED_MARKER.search(text[:2048]))


def _ipynb_code_complexity(text: str, tab_size: int = TAB_SIZE) -> float:
    """Sum indentation complexity over code cells only, ignoring the JSON envelope."""
    try:
        nb = json.loads(text)
    except json.JSONDecodeError:
        return 0.0
    total = 0.0
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        source = cell.get("source", "")
        lines = (
            source.splitlines() if isinstance(source, str) else [ln.rstrip("\n") for ln in source]
        )
        total += indentation_complexity_lines(lines, tab_size)
    return total


def indentation_complexity_lines(lines: Iterable[str], tab_size: int = TAB_SIZE) -> float:
    """Sum of logical indentation levels across non-blank lines.

    Cheap, language-agnostic complexity proxy: deeply nested code
    accumulates indentation.

    Args:
        lines: Source lines to measure (without trailing newlines).
        tab_size: Number of spaces a tab expands to.

    Returns:
        Sum of indentation levels across all non-blank lines.
    """
    total = 0
    for line in lines:
        if not line.strip():
            continue
        expanded = line.expandtabs(tab_size)
        total += (len(expanded) - len(expanded.lstrip(" "))) // tab_size
    return float(total)


def indentation_complexity(file_path: Path, tab_size: int = TAB_SIZE) -> float:
    """Sum of logical indentation levels across non-blank lines of a file.

    Returns 0.0 for missing or unreadable files (e.g. deleted within the
    analysis window), for binary content (NUL bytes present), for
    serialized-data/generated files (their indentation reflects file size,
    not code complexity), for .ipynb notebooks (scored over code cells only
    via _ipynb_code_complexity), and for files containing a generator marker
    in their first 2KB (e.g. protoc output, Rails schema.rb).

    Args:
        file_path: Path to the file to measure.
        tab_size: Number of spaces a tab expands to.

    Returns:
        Sum of indentation levels across all non-blank lines (or code cells
        for notebooks).
    """
    if _is_data_or_generated(file_path):
        return 0.0

    try:
        text = file_path.read_text(errors="ignore")
    except OSError:
        return 0.0

    if "\x00" in text:
        return 0.0

    if file_path.suffix.lower() == ".ipynb":
        return _ipynb_code_complexity(text, tab_size)

    if _has_generated_marker(text):
        return 0.0

    return indentation_complexity_lines(text.splitlines(), tab_size)
